# See https://cloud.google.com/cloud-build/docs/build-config
# Building multi-arch test images for non-x86 architecture

timeout: 3000s
options:
  substitution_option: ALLOW_LOOSE
  machineType: "N1_HIGHCPU_8"
steps:
  - name: "gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20211118-2f2d816b90"
    env:
      - HOME=/root # for docker buildx
    entrypoint: build
