name: release
on:
  push:
    tags:
      - "*"
jobs:
  publish:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod
      - run: make release-notes release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          allowUpdates: true
          artifacts: _output/releases/*
          bodyFile: release-notes.md
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: release-notes
          path: release-notes.md
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: build-artifacts
          path: _output
